stages:
  - triggers

frontend:
  stage: triggers
  trigger:
    include: ${CI_PROJECT_DIR}/apps/frontend/.gitlab-ci.yml
  rules:
    # - changes:
    #     - a/*

backend:
  stage: triggers
  trigger:
    include: ${CI_PROJECT_DIR}/apps/frontend/.gitlab-ci.yml
  rules:
    # - changes:
    #     - b/*