version: '3'

services:
  db:
    extends:
      file: ${BACKEND_APP_PATH}/docker-compose.yml
      service: db

  backend:
    extends:
      file: ${BACKEND_APP_PATH}/docker-compose.yml
      service: backend
