version: '3'

services:
  adapticc_db:
    image: postgres:latest
    restart: unless-stopped
    hostname: adapticc_db
    container_name: adapticc_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: adapticc
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    volumes:
      - ./db/dump/testdata.sql:/docker-entrypoint-initdb.d/testdata.sql

  adapticc_backend:
    hostname: adapticc_backend
    container_name: adapticc_backend
    working_dir: /backend
    build:
      context: ./
      dockerfile: ./build/images/backend/Dockerfile.hotrun
    depends_on:
      - adapticc_db
    expose:
      - 3011
    ports:
      - 3011:3011
    volumes:
      - ${BACKEND_APP_PATH}:/backend:rw

  adapticc_frontend_app:
    image: node:16.13.2-buster-slim
    hostname: adapticc_frontend_app
    container_name: adapticc_frontend_app
    command: bash -c "npm run start"
    environment:
      - NODE_ENV=dev
    expose:
      - 3000
    ports:
      - 3000:3000
    user: node
    working_dir: /usr/src/app
    volumes:
      - ${FRONTEND_APP_PATH}:/usr/src/app:rw

  # adapticc_nginx:
  #   hostname: adapticc_nginx
  #   container_name: adapticc_nginx
  #   build:
  #     context: ./
  #     dockerfile: ./nginx/Dockerfile
  #   depends_on:
  #     - adapticc_db
  #     - adapticc_backend
  #     - adapticc_frontend_app
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./logs/nginx/:/var/log/nginx:rw
  #     - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ${BACKEND_APP_PATH}:/var/www/adapticc-backend
  #     - ${FRONTEND_APP_PATH}:/var/www/adapticc-frontend
