stages:
  - build

build backend:
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  variables:
    CI_PROJECT_DIR_BACKEND: ${CI_PROJECT_DIR}/apps/backend

  stage: build

  script:
    - TAG=${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}
    - /kaniko/executor
      --context "${CI_PROJECT_DIR_BACKEND}"
      --dockerfile "${CI_PROJECT_DIR_BACKEND}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${TAG}"