version: '3.8'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    hostname: adapticc_db
    container_name: adapticc_db
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: adapticc
      POSTGRES_USER: adapticcuser
      POSTGRES_PASSWORD: dbpass
    volumes:
      - ./tests/integration/testdata/database.sql:/docker-entrypoint-initdb.d/database.sql

  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    hostname: adapticc_backend
    container_name: adapticc_backend
    command: bash -c "/sidecar/cerbos server --config=./policies/.cerbos.yaml & go run ./cmd/adapticc"
    working_dir: /backend
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./:/backend:rw