version: '3.8'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    hostname: adapticc_db
    container_name: adapticc_db
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: adapticc
      POSTGRES_USER: adapticcuser
      POSTGRES_PASSWORD: dbpass
    volumes:
      - ./tests/integration/testdata/database.sql:/docker-entrypoint-initdb.d/database.sql

  backend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: adapticc_backend
    container_name: adapticc_backend
    depends_on:
      - db
    ports:
      - 8080:8080