apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: "product"
  rules:
    - actions:
        - read
      effect: EFFECT_ALLOW
      roles:
        - product:viewer

    - actions:
        - create
        - read
        - update
        - delete
      effect: EFFECT_ALLOW
      roles:
        - product:editor